baseurl = "//cm.cecs.anu.edu.au/"
languageCode = "en-us"
title = "Computational Media Lab"
canonifyurls = true
disqusShortname = "computationalmedia"
[markup]
  defaultMarkdownHandler = "blackfriday"
